// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBondingCurveFactory$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBondingCurveFactory";
  readonly sourceName: "contracts/interfaces/IBondingCurveFactory.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"token","type":"address"},{"indexed":false,"internalType":"address","name":"pool","type":"address"},{"indexed":false,"internalType":"string","name":"name","type":"string"},{"indexed":false,"internalType":"string","name":"symbol","type":"string"},{"indexed":false,"internalType":"string","name":"iconURI","type":"string"},{"indexed":false,"internalType":"string","name":"projectURI","type":"string"},{"indexed":true,"internalType":"address","name":"creator","type":"address"}],"name":"TokenCreated","type":"event"},{"inputs":[{"internalType":"uint256","name":"index","type":"uint256"}],"name":"allTokens","outputs":[{"internalType":"address","name":"token","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"allTokensLength","outputs":[{"internalType":"uint256","name":"length","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"symbol","type":"string"},{"internalType":"string","name":"iconURI","type":"string"},{"internalType":"string","name":"projectURI","type":"string"},{"internalType":"uint256","name":"initialBuyAmountWei","type":"uint256"}],"name":"createToken","outputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"address","name":"pool","type":"address"}],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"getPool","outputs":[{"internalType":"address","name":"pool","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IBondingCurveFactory.sol";
  readonly buildInfoId: "solc-0_8_20-7c6ba6b5760947f9da86cecd5021ae0558bd8546";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBondingCurveFactory"]: IBondingCurveFactory$Type;
    ["contracts/interfaces/IBondingCurveFactory.sol:IBondingCurveFactory"]: IBondingCurveFactory$Type;
  }
}