// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBondingCurvePool$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBondingCurvePool";
  readonly sourceName: "contracts/interfaces/IBondingCurvePool.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"buyer","type":"address"},{"indexed":false,"internalType":"uint256","name":"hbarInWei","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"tokensOut","type":"uint256"}],"name":"Bought","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"seller","type":"address"},{"indexed":false,"internalType":"uint256","name":"tokensIn","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"hbarOutWei","type":"uint256"}],"name":"Sold","type":"event"},{"inputs":[{"internalType":"address","name":"to","type":"address"}],"name":"buy","outputs":[{"internalType":"uint256","name":"tokensOut","type":"uint256"}],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"uint256","name":"hbarInWei","type":"uint256"}],"name":"getPriceForBuy","outputs":[{"internalType":"uint256","name":"tokensOut","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"tokensIn","type":"uint256"}],"name":"getPriceForSell","outputs":[{"internalType":"uint256","name":"hbarOutWei","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"reserves","outputs":[{"internalType":"uint256","name":"hbarReserves","type":"uint256"},{"internalType":"uint256","name":"tokenReserves","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"uint256","name":"tokensIn","type":"uint256"}],"name":"sell","outputs":[{"internalType":"uint256","name":"hbarOutWei","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"token","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IBondingCurvePool.sol";
  readonly buildInfoId: "solc-0_8_20-7c6ba6b5760947f9da86cecd5021ae0558bd8546";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBondingCurvePool"]: IBondingCurvePool$Type;
    ["contracts/interfaces/IBondingCurvePool.sol:IBondingCurvePool"]: IBondingCurvePool$Type;
  }
}